name = "MultistageTrueAndErrorModels"
uuid = "fb4bbbae-812b-43d7-a03e-7ac3a4f04240"
version = "0.1.0"
authors = ["itsdfish"]

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
TrueAndErrorModels = "260ba6b7-9af7-473a-b238-1a1a0638f266"

[sources]
TrueAndErrorModels = {url = "https://github.com/itsdfish/TrueAndErrorModels.jl"}

[compat]
ArgCheck = "2.5.0"
Distributions = "0.25.123"
DocStringExtensions = "0.9.5"
PrettyTables = "3.3.2"
TrueAndErrorModels = "0.2.22"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
